### ISSUE TITLE
Micronaut configuration not being pulled by name

### ISSUE THREAD

**Issue by braxma** [micronaut-projects/micronaut-mongodb#405]
### Expected Behavior

expect pulled uri in test 

> mongodb://localhost:27017/base

### Actual Behaviour

actual pulled uri in test 

> mongodb://user:password@prodaction-host:27017/base

### Steps To Reproduce

When you have such a configuration
```
mongodb:
  servers:
    test:
      uri: 'mongodb://localhost:27017/base'
    dev:
      uri: 'mongodb://user:password@prodaction-host:27017/base'
```
      
and test annotated with 
`@MicronautTest(environments = "test")`

### Environment Information

ubuntu, jdk-17
```
dependencies {
    annotationProcessor("io.micronaut:micronaut-http-validation")
    implementation("io.micronaut:micronaut-http-server-netty")
    implementation("io.micronaut:micronaut-http-client")
    implementation("io.micronaut:micronaut-jackson-databind")
    implementation("jakarta.annotation:jakarta.annotation-api")
    // logging
    runtimeOnly("ch.qos.logback:logback-classic")
    // database
    annotationProcessor("io.micronaut.data:micronaut-data-document-processor")
    implementation("io.micronaut.data:micronaut-data-mongodb")
    implementation("org.mongodb:mongodb-driver-sync")

    testImplementation("org.testcontainers:junit-jupiter")
    testImplementation("org.testcontainers:mongodb")
    testImplementation("org.testcontainers:testcontainers")
}
```

### Version

3.9.1
